# toml 转 struct : https://github.com/xuri/toml-to-go

[workspace]
# mp4 local file directory
mp4 = ""
# mp3 local file directory
mp3 = ""
# ffmpeg local file, download for https://www.ffmpeg.org/download.html
ffmpeg = ""

[aliyun.user]
accessKeyID = "@"
accessKeySecret = "@"

# https://ai.aliyun.com/nls/filetrans
[aliyun.ai]
regionId = "@"
appkey = "@"

# https://www.aliyun.com/product/oss
[aliyun.oss]
endpoint = "@"
bucketName = "@"

# db
[db]
type = "sqlite"
addr = "/sqlite.db"
port = 0
username = ""
password = ""
database = ""
charset = "utf8"

